### ISSUE TITLE
Deprecations in Eigen3 and Python library usage

### ISSUE THREAD

**Issue by andrewfullard** [Plant-Root-Soil-Interactions-Modelling/CPlantBox#125]
I've been working to compile this software on a HPCC running CentOS 7 and run into a few errors if specific dependencies are used. It would be helpful to provide maximum compatible versions for:

- Eigen3, fails the make process if it is version 3.4+. Eigen3 is also not mentioned as a dependency in the build instructions
- Python, fails the make process for version 3.12

There is also no mention of the Python dependencies such as vtk

**Comment by m-giraud** [comment]
Thanks for bringing the issue to our attention.
We updated the readme file, making it clearer which is the prefered install method. Using the python install script should check for the dependencies and solve the problem with python3.12. We also added a requirements.txt file.
Which version of Eigen3 are you using exactly?

**Comment by andrewfullard** [comment]
Thank you for the response and update! Unfortunately while I don't recall which versions of Eigen3 failed, I had success with this environment: `GCCcore/11.2.0 Eigen/3.3.9 CMake/3.22.1`.
