### ISSUE TITLE
Number of laterals (leaves) depends on timestep size

### ISSUE THREAD

**Issue by ArnaudBvr** [Plant-Root-Soil-Interactions-Modelling/CPlantBox#127]
Hi, 

When running a script to simulate lettuce plants (same as my previous issue), I noticed that the number of laterals seems to depend on timestep size which looks like a bug more than a feature ?

Here is a table that recaps the number of leaves at the final timestep (tf = 30 days). All other parameters are left equal, only the timestep size changes. The expected number of leaves is computed as: (lmax-la-lb)/ln + 1 (per the CRootBox paper, Schnepf et al. 2018) and is approx. 12.6.

| dt [d] | Number of leaves |
| ---- | ---- |
| 10 | 13 |
| 5 | 12 |
| 1 | 11 |
| 0.1 | 10 |
| 0.01 | 10 |
| 0.001 | 10 |

My understanding is that a smaller timestep could interact with the dx and dxMin parameters of the main stem and thus have an impact on the emergence of laterals ?

Edit to add the parameter file and associated script
[lactuca_num_leaves.zip](https://github.com/Plant-Root-Soil-Interactions-Modelling/CPlantBox/files/14282190/lactuca_num_leaves.zip)

**Comment by m-giraud** [comment]
Hello!
I ran the script and parameter file you gave in [the previous issue](https://github.com/Plant-Root-Soil-Interactions-Modelling/CPlantBox/issues/126), except that I added:
`parameter name="delayDefinition" value="2"/`
to the seed parameters.
 for your stem you have (lmax-la-lb)/ln + 1 = ((5-0.1-0.1)/0.5+1=10.6 
I tested the 6 time steps and I got :
| 10     | 11 |
| 1       | 11 |
| 0.1    | 10 |
| 0.01  | 10 |
| 0.001 | 10 |
maybe you made some changes to the parameter or python files which explaines our different results? Also, which CPlantBox branch are you on?

**Comment by ArnaudBvr** [comment]
sorry I forgot to upload my script and parameter files, I edited the question to add them

**Comment by ArnaudBvr** [comment]
I did consider that possibility and I think it's something else because reading the documentation for numpy.arange : 

> `stop` : integer or real
End of interval. The interval **does not include** this value, except in some cases where step is not an integer and floating point round-off affects the length of out.

Which is why I added `+dt` to the `stop` argument.

When I define several time steps in a list and try them out like this: 
```
list_dt = [10, 1, 0.1, 0.01]
for dt in list_dt:
    t = np.arange(start=0, stop=30, step=dt)
    print(f'dt={dt} tmax = {max(t)}')
```

I get: 
| dt   | t max |
|------|-------|
| 10   | 20    |
| 1    | 29    |
| 0.1  | 29.9  |
| 0.01 | 29.99 |

But when I run: 
```
for dt in list_dt:
    t = np.arange(start=0, stop=30+dt, step=dt)
    print(f'dt={dt} tmax = {max(t)}')
```

I get the expected final time (the same for all simulations): 
| dt   | t max |
|------|-------|
| 10   | 30    |
| 1    | 30    |
| 0.1  | 30.0  |
| 0.01 | 30.0 |

So the simulations are actually of the same duration. 

I'll dig a little deeper with the verbose output of the `simulate()` method.

**Comment by m-giraud** [comment]
What is importnant to keep in mind is that the output of 'np.arange(start=0, stop=30+dt, step=dt)' will give you the plant age at the beginning of the time step. And you want to have an equal plant age at the end of the last time step not at the beginning of the last time step

**Comment by ArnaudBvr** [comment]
You were right, there was some confusion between the time vector `t` and `simulate(dt)` on my part. 

Sorry for the trouble !

**Comment by m-giraud** [comment]
i m  happy I could help!
