### ISSUE TITLE
can't find function r.SoilFluxes

### ISSUE THREAD

**Issue by noemiversluijs** [Plant-Root-Soil-Interactions-Modelling/CPlantBox#144]
I am experiencing two issues: 
1. In example7b_coupling.py, the soil flux is calculated by this piece of code:  

    fluxes = r.soilFluxes(rs_age + t, rx, sx, False)
    s.setSource(fluxes)  # richards.py
    s.solve(dt)
    sx = s.getSolutionHead()  # richards.py

Where r = XylemFluxPython(rs), which is imported from functional.xylem_flux

However, I can't seem to find the soilFluxes() function in the functional.xylem_flux script, could anyone tell me where this function is defined? 

2. In all of the examples, one of the first lines is "import plantbox as pb", but I can't seem to locate plantbox. It is not in my python environment, but it does work so it must be located somewhere.

**Comment by m-giraud** [comment]
Dear noemiversluijs,
1) the soilFluxes functin is defined in C++, in the file  [XylemFlux.cpp](https://github.com/Plant-Root-Soil-Interactions-Modelling/CPlantBox/blob/master/src/functional/XylemFlux.cpp)
2) Common explenations and solutions for the 'Module not found error' issue are described in the wiki: https://github.com/Plant-Root-Soil-Interactions-Modelling/CPlantBox/wiki/Common-issues#module-not-found-error

You can try and implementing these solutions. 
If they do not solve your problem, could you give complementatry information on how you are running the scripts? (via VScode, ubuntu terminal...)? 
And do you see a plantbox.cpython-***-x86_64-linux-gnu.so file in the CPlantBox folder?

**Comment by m-giraud** [comment]
Can I close this issue or do you still have a problem related to the message above?

**Comment by noemiversluijs** [comment]
The issue is solved, thank you!

**Comment by m-giraud** [comment]
great!
