### ISSUE TITLE
error in make command

### ISSUE THREAD

**Issue by nana784365** [Plant-Root-Soil-Interactions-Modelling/CPlantBox#36]
Hi.
I want to build CPlantBox on my system(macOS).
I succeed  "cmake", but get this error while trying "make" :

In file included from /Users/xxx/CPlantBox/src/RootSystem.cpp:2:
In file included from /Users/xxx/CPlantBox/src/RootSystem.h:5:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/stack:92:
/Library/Developer/CommandLineTools/usr/include/c++/v1/deque:272:34: error: 
      invalid application of 'sizeof' to an incomplete type
      'CPlantBox::RootSystemState'
  static const _DiffType value = sizeof(_ValueType) < 256 ? 4096 / sizeo...
                                 ^~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/deque:282:32: note: in
      instantiation of template class
      'std::__1::__deque_block_size<CPlantBox::RootSystemState, long>' requested
      here
                               __deque_block_size<_ValueType, _DiffType>::value
                               ^

and so on.

Is there any solution on these problem?
Thanks for the help!

**Comment by DanielLeitner** [comment]
not sure about the problem. but, I replaced the std::stack (which seems to be problematic) by a std:vector. I could not test it, since I do not develop on mac, but I hope it will work

**Comment by nana784365** [comment]
Hi,
Thanks for your help, I could succeed!
