### ISSUE TITLE
Can not start the program

### ISSUE THREAD

**Issue by m-ingenbleek** [Plant-Root-Soil-Interactions-Modelling/CPlantBox#80]
Hello,

I have a problem that I can not start the program.
I done the steps from the README:
**"cmake . && make"**
in the root folder, and run some Python tutorial examples (see tutorial/latex/PlantBox_RootSytem), e.g

**"cd tutorial/examples/python"
"python3 example1a.py"**

but in the last step give me the error:
_**Traceback (most recent call last):
  File "/home/m.ingenbleek/CPlantBox-1.1/tutorial/examples/python/example1a_small.py", line 4, in <module>
    import plantbox as pb
ModuleNotFoundError: No module named 'plantbox'**_

versions:  Linux 22.04 Python 3.10.04

Any suggestions here?

Thanks!

**Comment by m-giraud** [comment]
Hello!
It could be linked to the python version, which is not supported by the pybind11 we have.
Could you create a conda environment with python 3.8, delete the "CPlantBox/CMakeCache.txt" file and launch again "cmake ." then "make ."? 
If you get again the ModuleNotFoundError, could you copy here the output you got when running "cmake ." and "make ."?

**Comment by m-giraud** [comment]
can I close the issue?

**Comment by m-ingenbleek** [comment]
Thanks for your help. 
The program only works with Python 3.8. 
Issue can be closed.

**Comment by m-giraud** [comment]
now cplantbox works with python3.10
